---@class OverTimeEffect
---@field timeRemaining number The game time length the effect should remain active
---@field amount number The amount the effect the stat should increase by per second
---@field stat string String name of the stat this effect changes